[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.poetry]
name = "llambdao"
version = "0.1.0"
description = "A Python framework for implementing the ideas to be discussed in LLAMBDAO: Large Language Agents Modulating Behaviour in Decentralized Autonomous Organizations"
authors = ["Shaman AI <hello@shaman.ai>"]
license = "BUSL-1.1"
readme = "README.md"
packages = [{ include = "llambdao" }]

[tool.poetry.dependencies]
eventemitter = "^0.2.0"
pydantic = "^1.10.7"
python = "^3.10.9"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
faiss-cpu = "^1.7.4"
ipdb = "^0.13.13"
ipython = "^8.12.0"
jupyter = "^1.0.0"
mypy = "^1.2.0"
pytest = "^7.3.1"
python-dotenv = "^1.0.0"
ruff = "^0.0.261"
setuptools = "^67.6.1"
streamlit = "^1.21.0"
types-pyyaml = "^6.0.12.9"
openai = "^0.27.7"
wikipedia = "^1.4.0"

[tool.poetry.group.ray]
optional = true

[tool.poetry.group.ray.dependencies]
ray = "^2.4.0"

[tool.poetry.group.langchain]
optional = true

[tool.poetry.group.langchain.dependencies]
langchain = { git = "https://github.com/hwchase17/langchain.git" }
