[tool.poetry]
name = "dao-agent"
version = "0.1.0"
description = "DAO Agent: A framework for building decentralized autonomous organizations of AI agents."
authors = ["Shaman AI <hello@shaman.ai>"]
license = "BUSL-1.1"
readme = "README.md"
packages = [{ include = "dao_agent" }]

[tool.ruff]
line-length = 100

[tool.poetry.dependencies]
python = "^3.10.9"
pydantic = "^1.10.7"
langchain = { git = "https://github.com/hwchase17/langchain.git", rev = "7bcf238" }
eventemitter = "^0.2.0"
ray = "^2.4.0"

[tool.poetry.group.typing]
optional = true

[tool.poetry.group.typing.dependencies]
mypy = "^1.2.0"
types-pyyaml = "^6.0.12.9"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
setuptools = "^67.6.1"
ipdb = "^0.13.13"
black = "^23.3.0"
ipython = "^8.12.0"
ruff = "^0.0.261"
streamlit = "^1.21.0"
pytest = "^7.3.1"
faiss-cpu = "^1.7.4"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
