import pytest

from llegos.fipa.contract_net import (
    CFP,
    Accept,
    AcceptProposal,
    ContractNet,
    Failure,
    InformDone,
    InformResult,
    Propose,
    Refuse,
    RejectProposal,
    Request,
    Response,
)


@pytest.mark.asyncio
async def test_contract_net():
    contract_net = ContractNet(...)
    request = Request(body="A task")
    async for reply in contract_net.receive(request):
        "Access all the nested replies generated by the agent network as they happen"
        match reply:
            case CFP():
                print("Got a call for proposal!")
            case Accept():
                print("Got an acceptance!")
            case Refuse():
                print("Got a refusal!")
            case Propose():
                print("Got a proposal!")
            case AcceptProposal():
                print("Proposal accepted!")
            case RejectProposal():
                print("Proposal rejected!")
            case Failure():
                print("Task failed!")
            case InformDone():
                print("Task done!")
            case InformResult():
                print("Task done!")
            case Response():
                print("Task done!")
            case AcceptProposal():
                print("Proposal accepted!")
            case RejectProposal():
                print("Proposal rejected!")
            case Failure():
                print("Task failed!")
            case InformDone():
                print("Task done!")
            case InformResult():
                print("Task done!")
            case Response():
                print("Response received!")
            case Response():
                print("Response received!")
